apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksMundosE
  region: us-east-1

vpc:
  id: $VPC_NAME # Reemplaza con el ID de tu VPC
  subnets:
    private:
      us-east-1a:
        id: $PRIVATE1 # Reemplaza con el ID de tu subnet privada en us-east-1a
      us-east-1b:
        id: $PRIVATE2 # Reemplaza con el ID de tu subnet privada en us-east-1b
      us-east-1c:
        id: $PRIVATE3 # Reemplaza con el ID de tu subnet privada en us-east-1c
    public:
      us-east-1a:
        id: $PUBLIC1 # Reemplaza con el ID de tu subnet pública en us-east-1a
      us-east-1b:
        id: $PUBLIC2 # Reemplaza con el ID de tu subnet pública en us-east-1b
      us-east-1c:
        id: $PUBLIC3 # Reemplaza con el ID de tu subnet pública en us-east-1c

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 3
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: $KEY_NAME
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
        cloudWatch: true
        awsLoadBalancerController: true
addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
iam:
  withOIDC: true
