name: Instancia EC2 Terraform

on:
  push:
    branches:
      - main  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        AWSACCESSKEYID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWSSECRETACCESSKEYID: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  

    - name: Terraform Init
      run: terraform init

    - name: Terraform validate
      run: terraform validate
      
    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
